/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vuelo.Vista;

import java.beans.PropertyVetoException;
import vuelo.Modelo.Conexion;
import vuelo.Modelo.ClienteData;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import vuelo.Control.Clientes;


/**
 *
 * @author Sebastian
 */
public class F_Clientes extends javax.swing.JInternalFrame {
    
    
    public int idCliente;
    /**
     * Creates new form F_Clientes
     */
    public F_Clientes() {
        initComponents();
        btnmodificar.setEnabled(false);//deshabilta el boton modificar
        btneliminar.setEnabled(false);//deshabilta el boton eliminar
    }
    
    
    void LimpiarCajas(){
    txtnombre.setText("");
    txtpasaporte.setText("");
    txttarjeta.setText("");
    lblid.setText(""); //Importante: limpiar la etiqueta contenedora de mi id de tabla
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnguardar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        txtnombre = new javax.swing.JTextField();
        txtpasaporte = new javax.swing.JTextField();
        txttarjeta = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        lblid = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jLabel1.setText("CLIENTES");

        jLabel2.setText("NOMBRE Y APELLIDO");

        jLabel3.setText("Nº DE PASAPORTE *");

        jLabel4.setText("TARJETA");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        btnguardar.setMnemonic('g');
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnmodificar.setMnemonic('m');
        btnmodificar.setText("Modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btneliminar.setMnemonic('e');
        btneliminar.setText("Eliminar Registro");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnguardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnmodificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btneliminar)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardar)
                    .addComponent(btnmodificar)
                    .addComponent(btneliminar))
                .addContainerGap())
        );

        btnbuscar.setMnemonic('s');
        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        lblid.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        lblid.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnombre)
                            .addComponent(txttarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpasaporte, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnbuscar)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(283, 283, 283)
                        .addComponent(lblid, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblid, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpasaporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnbuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txttarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        
        if ("".equals(txtpasaporte.getText())){ //Verifico qeu el campo de texto pasaporte no este vacio
           JOptionPane.showMessageDialog(null, "El campo Nº de pasaporte no puede estar vacio.");
        }else{ 
        Conexion conexion;//conexion
        try {
        conexion = new Conexion("jdbc:mysql://siscollege.dynu.net:3306/vuelos", "connect", "123456"); // paso el dato a las variables de la clase conexion
        ClienteData clienteData = new ClienteData(conexion);
        Clientes cliente = new Clientes(txtnombre.getText(), txtpasaporte.getText(), txttarjeta.getText()); // Paso los valores de las cajas
        clienteData.guardarCliente(cliente);
        LimpiarCajas(); // limpio los texboxs
          } catch (ClassNotFoundException ex) {
            Logger.getLogger(F_Clientes.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Error al instanciar la clase conexion: " + ex.getMessage());
        }
      }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
            //EVENTOS
            
            btnguardar.setEnabled(false); //bloquear boton guardar
            btnmodificar.setEnabled(true); //habilito el boton modificar
            btneliminar.setEnabled(true); //habilito el boton eliminar
           if ("".equals(txtpasaporte.getText())){ //Verifico qeu el campo de texto pasaporte no este vacio
                JOptionPane.showMessageDialog(null, "El campo Nº de pasaporte no puede estar vacio.");
                btnmodificar.setEnabled(false);
                btneliminar.setEnabled(false);
                btnguardar.setEnabled(true);
           }else{ 
        Conexion conexion;
        try {
            conexion = new Conexion("jdbc:mysql://siscollege.dynu.net:3306/vuelos", "connect", "123456"); // paso el dato a las variables de la clase conexion
            ClienteData clienteData = new ClienteData(conexion);
            Clientes cliente = new Clientes(txtpasaporte.getText()); // le paso al constructor la busqueda por pasaporte
            clienteData.obtenerCliente(cliente);
            lblid.setText(Integer.toString(cliente.getIdCliente())); // coloco en el label el id del registro
            txtnombre.setText(cliente.getNombre()); 
            txttarjeta.setText(cliente.getTarjeta());        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(F_Clientes.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Error al instanciar la clase conexion: " + ex.getMessage());
        }
           } 
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        // TODO add your handling code here:
         Conexion conexion;
        try {
            conexion = new Conexion("jdbc:mysql://siscollege.dynu.net:3306/vuelos", "connect", "123456"); // paso el dato a las variables de la clase conexion
            ClienteData clienteData = new ClienteData(conexion);
            Clientes cliente = new Clientes(Integer.parseInt(lblid.getText()), txtnombre.getText(), txtpasaporte.getText(), txttarjeta.getText()); // llamo al constructor //convierto el String a entero con integer parseint
            clienteData.modificarCliente(cliente);  // llamo al metodo modificar cliente creado en ClienteData                                                                                             
            LimpiarCajas(); //limpio los texBox
            System.out.println("Registro Modificado Correctamente");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(F_Clientes.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Error al instanciar la clase conexion: " + ex.getMessage());
        }
        
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
          Conexion conexion;
        try {
            conexion = new Conexion("jdbc:mysql://siscollege.dynu.net:3306/vuelos", "connect", "123456"); // paso el dato a las variables de la clase conexion
            ClienteData clienteData = new ClienteData(conexion);
            Clientes cliente = new Clientes(Integer.parseInt(lblid.getText()), txtnombre.getText(), txtpasaporte.getText(), txttarjeta.getText());
            clienteData.eliminarCliente(cliente);
            LimpiarCajas(); // limpio los texbox
            System.out.println("Registro Eliminado Correctamente");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(F_Clientes.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Error al instanciar la clase conexion: " + ex.getMessage());
        } 
    }//GEN-LAST:event_btneliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblid;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtpasaporte;
    private javax.swing.JTextField txttarjeta;
    // End of variables declaration//GEN-END:variables
}
